// Generated by setup.html on 2026-09-11T12:33:41.057Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://lgljraseqvtjirhuqzss.supabase.co";
window.SUPABASE_KEY = "sb_publishable_k31_3qoKXw3bMcFSQkgl9Q_0vPbu2Iz";
